In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\Shree\OneDrive\Desktop\Class Projects\flipkart_sales_dataset.csv")

In [3]:
df.head()

,Order ID,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating,Month,Year,Profit (INR),Discount %,Customer Segment,Region
0,ORD00001,Educational Book,Books,49069.56,2,98139.12,2024-09-12,Debit Card,3.5,September,2024,19627.824,11,Online,West
1,ORD00002,Jeans,Clothing,12755.85,4,51023.40,2024-12-18,UPI,3.9,December,2024,10204.680,24,Wholesale,North
2,ORD00003,Face Cream,Beauty,11092.19,4,44368.76,2024-05-18,Debit Card,4.4,May,2024,8873.752,19,Online,South
3,ORD00004,Smartwatch,Electronics,32657.81,1,32657.81,2024-11-08,Debit Card,3.2,November,2024,6531.562,15,Online,North
4,ORD00005,Cookware Set,Home & Kitchen,26590.08,3,79770.24,2024-12-27,UPI,3.1,December,2024,15954.048,12,Retail,North

In [4]:
df.tail()

,Order ID,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating,Month,Year,Profit (INR),Discount %,Customer Segment,Region
995,ORD00996,Smartphone,Electronics,28995.81,3,86987.43,2025-01-13,COD,5.0,January,2025,17397.486,28,Wholesale,West
996,ORD00997,Perfume,Beauty,32799.51,2,65599.02,2024-12-18,Wallet,2.4,December,2024,13119.804,23,Wholesale,North
997,ORD00998,Face Cream,Beauty,40840.80,1,40840.80,2024-07-26,UPI,3.1,July,2024,8168.160,11,Retail,West
998,ORD00999,Cookware Set,Home & Kitchen,34741.79,4,138967.16,2024-10-02,Net Banking,3.2,October,2024,27793.432,7,Wholesale,East
999,ORD01000,Table Lamp,Home & Kitchen,16698.12,4,66792.48,2024-03-26,Credit Card,1.6,March,2024,13358.496,19,Wholesale,East

In [5]:
df.columns

Index(['Order ID', 'Product Name', 'Category', 'Price (INR)', 'Quantity Sold',
       'Total Sales (INR)', 'Order Date', 'Payment Method', 'Customer Rating',
       'Month', 'Year', 'Profit (INR)', 'Discount %', 'Customer Segment',
       'Region'],
      dtype='object')

In [6]:
df.shape

(1000, 15)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order ID           1000 non-null   object
 1   Product Name       1000 non-null   object
 2   Category           1000 non-null   object
 3   Price (INR)        1000 non-null   float64
 4   Quantity Sold      1000 non-null   int64
 5   Total Sales (INR)  1000 non-null   float64
 6   Order Date         1000 non-null   object
 7   Payment Method     1000 non-null   object
 8   Customer Rating    1000 non-null   float64
 9   Month              1000 non-null   object
 10  Year               1000 non-null   int64
 11  Profit (INR)       1000 non-null   float64
 12  Discount %         1000 non-null   int64
 13  Customer Segment   1000 non-null   object
 14  Region             1000 non-null   object
dtypes: float64(4), int64(3), object(8)
memory usage: 117.3+ KB

In [9]:
df.describe()

,Price (INR),Quantity Sold,Total Sales (INR),Customer Rating,Year,Profit (INR),Discount %
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,24520.258260,3.097000,75213.112740,3.011100,2024.103000,15042.622548,17.699000
std,14187.611227,1.410525,59457.598352,1.145408,0.304111,11891.519670,7.847801
min,139.850000,1.000000,419.550000,1.000000,2024.000000,83.910000,5.000000
25%,12378.905000,2.000000,28581.765000,2.000000,2024.000000,5716.353000,11.000000
50%,24650.015000,3.000000,57358.300000,3.100000,2024.000000,11471.660000,18.000000
75%,35981.925000,4.000000,110618.595000,4.000000,2024.000000,22123.719000,25.000000
max,49911.750000,5.000000,243903.900000,5.000000,2025.000000,48780.780000,30.000000

### Data Cleaning

In [10]:
df.isnull().sum() # no null values

Order ID             0
Product Name         0
Category             0
Price (INR)          0
Quantity Sold        0
Total Sales (INR)    0
Order Date           0
Payment Method       0
Customer Rating      0
Month                0
Year                 0
Profit (INR)         0
Discount %           0
Customer Segment     0
Region               0
dtype: int64

In [15]:
del df["Order ID"]

In [16]:
df.head()

,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating,Month,Year,Profit (INR),Discount %,Customer Segment,Region
0,Educational Book,Books,49069.56,2,98139.12,2024-09-12,Debit Card,3.5,September,2024,19627.824,11,Online,West
1,Jeans,Clothing,12755.85,4,51023.40,2024-12-18,UPI,3.9,December,2024,10204.680,24,Wholesale,North
2,Face Cream,Beauty,11092.19,4,44368.76,2024-05-18,Debit Card,4.4,May,2024,8873.752,19,Online,South
3,Smartwatch,Electronics,32657.81,1,32657.81,2024-11-08,Debit Card,3.2,November,2024,6531.562,15,Online,North
4,Cookware Set,Home & Kitchen,26590.08,3,79770.24,2024-12-27,UPI,3.1,December,2024,15954.048,12,Retail,North

In [21]:
df['Order Date'] = pd.to_datetime(df['Order Date'])

In [18]:
import datetime

In [22]:
df['Year'] = df['Order Date'].dt.year

In [23]:
df['Month'] = df['Order Date'].dt.month

In [24]:
df['day_of_week'] = df['Order Date'].dt.weekday

In [25]:
df['is_weekend'] = df['day_of_week'].apply(lambda x:1 if x >= 5 else 0)

In [26]:
df.head()

,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating,Month,Year,Profit (INR),Discount %,Customer Segment,Region,day_of_week,is_weekend
0,Educational Book,Books,49069.56,2,98139.12,2024-09-12,Debit Card,3.5,9,2024,19627.824,11,Online,West,3,0
1,Jeans,Clothing,12755.85,4,51023.40,2024-12-18,UPI,3.9,12,2024,10204.680,24,Wholesale,North,2,0
2,Face Cream,Beauty,11092.19,4,44368.76,2024-05-18,Debit Card,4.4,5,2024,8873.752,19,Online,South,5,1
3,Smartwatch,Electronics,32657.81,1,32657.81,2024-11-08,Debit Card,3.2,11,2024,6531.562,15,Online,North,4,0
4,Cookware Set,Home & Kitchen,26590.08,3,79770.24,2024-12-27,UPI,3.1,12,2024,15954.048,12,Retail,North,4,0

In [27]:
# Total revenue check (if needed)
df['calculated_sales'] = df['Price (INR)'] * df['Quantity Sold']

In [28]:
# Discount amount (actual loss due to discount)
df['discount_amount'] = (df['Price (INR)'] * df['Discount %']) / 100

In [29]:
# Final price after discount
df['discounted_price'] = df['Price (INR)'] - df['discount_amount']

In [30]:
# Profit per unit
df['profit_per_unit'] = df['Profit (INR)'] / df['Quantity Sold']

In [31]:
# Quantity per order indicator
df['avg_order_value'] = df['Total Sales (INR)'] / df['Quantity Sold']

In [32]:
# Value per rating (how much revenue per rating point)
df['value_per_rating'] = df['Total Sales (INR)'] / df['Customer Rating']

In [33]:
df.head()

,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating,Month,Year,...,Customer Segment,Region,day_of_week,is_weekend,calculated_sales,discount_amount,discounted_price,profit_per_unit,avg_order_value,value_per_rating
0,Educational Book,Books,49069.56,2,98139.12,2024-09-12,Debit Card,3.5,9,2024,...,Online,West,3,0,98139.12,5397.6516,43671.9084,9813.912,49069.56,28039.748571
1,Jeans,Clothing,12755.85,4,51023.40,2024-12-18,UPI,3.9,12,2024,...,Wholesale,North,2,0,51023.40,3061.4040,9694.4460,2551.170,12755.85,13082.923077
2,Face Cream,Beauty,11092.19,4,44368.76,2024-05-18,Debit Card,4.4,5,2024,...,Online,South,5,1,44368.76,2107.5161,8984.6739,2218.438,11092.19,10083.809091
3,Smartwatch,Electronics,32657.81,1,32657.81,2024-11-08,Debit Card,3.2,11,2024,...,Online,North,4,0,32657.81,4898.6715,27759.1385,6531.562,32657.81,10205.565625
4,Cookware Set,Home & Kitchen,26590.08,3,79770.24,2024-12-27,UPI,3.1,12,2024,...,Retail,North,4,0,79770.24,3190.8096,23399.2704,5318.016,26590.08,25732.335484

In [34]:
# Previous sales
df['lag_1_sales'] = df['Total Sales (INR)'].shift(1)
df['lag_2_sales'] = df['Total Sales (INR)'].shift(2)

In [35]:
# Previous profit
df['lag_1_profit'] = df['Profit (INR)'].shift(1)

In [36]:
# Previous quantity
df['lag_1_quantity'] = df['Quantity Sold'].shift(1)

In [37]:
df['rolling_mean_sales_3'] = df['Total Sales (INR)'].rolling(window=3).mean()
df['rolling_mean_sales_7'] = df['Total Sales (INR)'].rolling(window=7).mean()

In [38]:
# Rolling sum
df['rolling_sum_sales_7'] = df['Total Sales (INR)'].rolling(window=7).sum()

In [39]:
# Rolling profit trend
df['rolling_mean_profit_3'] = df['Profit (INR)'].rolling(3).mean()

In [41]:
df.head(10)

,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating,Month,Year,...,avg_order_value,value_per_rating,lag_1_sales,lag_2_sales,lag_1_profit,lag_1_quantity,rolling_mean_sales_3,rolling_mean_sales_7,rolling_sum_sales_7,rolling_mean_profit_3
0,Educational Book,Books,49069.56,2,98139.12,2024-09-12,Debit Card,3.5,9,2024,...,49069.56,28039.748571,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Jeans,Clothing,12755.85,4,51023.40,2024-12-18,UPI,3.9,12,2024,...,12755.85,13082.923077,98139.12,NaN,19627.824,2.0,NaN,NaN,NaN,NaN
2,Face Cream,Beauty,11092.19,4,44368.76,2024-05-18,Debit Card,4.4,5,2024,...,11092.19,10083.809091,51023.40,98139.12,10204.680,4.0,64510.426667,NaN,NaN,12902.085333
3,Smartwatch,Electronics,32657.81,1,32657.81,2024-11-08,Debit Card,3.2,11,2024,...,32657.81,10205.565625,44368.76,51023.40,8873.752,4.0,42683.323333,NaN,NaN,8536.664667
4,Cookware Set,Home & Kitchen,26590.08,3,79770.24,2024-12-27,UPI,3.1,12,2024,...,26590.08,25732.335484,32657.81,44368.76,6531.562,1.0,52265.603333,NaN,NaN,10453.120667
5,Mixer Grinder,Home & Kitchen,10475.03,2,20950.06,2024-10-22,Wallet,1.7,10,2024,...,10475.03,12323.564706,79770.24,32657.81,15954.048,3.0,44459.370000,NaN,NaN,8891.874000
6,Sneakers,Clothing,38647.72,3,115943.16,2024-07-04,Wallet,2.0,7,2024,...,38647.72,57971.580000,20950.06,79770.24,4190.012,2.0,72221.153333,63264.650000,442852.55,14444.230667
7,Table Lamp,Home & Kitchen,24818.59,3,74455.77,2024-12-27,Debit Card,2.4,12,2024,...,24818.59,31023.237500,115943.16,20950.06,23188.632,3.0,70449.663333,59881.314286,419169.20,14089.932667
8,Jacket,Clothing,1987.39,2,3974.78,2025-01-18,Debit Card,2.6,1,2025,...,1987.39,1528.761538,74455.77,115943.16,14891.154,3.0,64791.236667,53160.082857,372120.58,12958.247333
9,Tablet,Electronics,26876.51,2,53753.02,2024-03-14,Debit Card,4.0,3,2024,...,26876.51,13438.255000,3974.78,74455.77,794.956,2.0,44061.190000,54500.691429,381504.84,8812.238000

### Encoding

In [56]:
df = pd.get_dummies(df, columns=['Category','Region','Payment Method','Customer Segment'], drop_first=True)

In [57]:
df.head()

,Product Name,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Customer Rating,Month,Year,Profit (INR),Discount %,...,Region_North,Region_South,Region_West,Payment Method_Credit Card,Payment Method_Debit Card,Payment Method_Net Banking,Payment Method_UPI,Payment Method_Wallet,Customer Segment_Retail,Customer Segment_Wholesale
0,Educational Book,1.731200,-0.778114,0.385779,2024-09-12,0.427049,9,2024,0.385779,-0.854042,...,False,False,True,False,True,False,False,False,False,False
1,Jeans,-0.829618,0.640508,-0.407043,2024-12-18,0.776444,12,2024,-0.407043,0.803302,...,True,False,False,False,False,False,True,False,False,True
2,Face Cream,-0.946938,0.640508,-0.519022,2024-05-18,1.213188,5,2024,-0.519022,0.165862,...,False,True,False,False,True,False,False,False,False,False
3,Smartwatch,0.573854,-1.487424,-0.716083,2024-11-08,0.165002,11,2024,-0.716083,-0.344090,...,True,False,False,False,True,False,False,False,False,False
4,Cookware Set,0.145962,-0.068803,0.076683,2024-12-27,0.077653,12,2024,0.076683,-0.726554,...,True,False,False,False,False,False,True,False,True,False

### Feature Scaling

In [58]:
num_cols = [
    'Price (INR)', 'Quantity Sold', 'Total Sales (INR)',
    'Profit (INR)', 'Discount %', 'Customer Rating'
]

In [59]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df[num_cols] = scaler.fit_transform(df[num_cols])

In [45]:
df.head(10)

,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating,Month,Year,...,avg_order_value,value_per_rating,lag_1_sales,lag_2_sales,lag_1_profit,lag_1_quantity,rolling_mean_sales_3,rolling_mean_sales_7,rolling_sum_sales_7,rolling_mean_profit_3
0,Educational Book,Books,1.731200,-0.778114,0.385779,2024-09-12,Debit Card,0.427049,9,2024,...,49069.56,28039.748571,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Jeans,Clothing,-0.829618,0.640508,-0.407043,2024-12-18,UPI,0.776444,12,2024,...,12755.85,13082.923077,98139.12,NaN,19627.824,2.0,NaN,NaN,NaN,NaN
2,Face Cream,Beauty,-0.946938,0.640508,-0.519022,2024-05-18,Debit Card,1.213188,5,2024,...,11092.19,10083.809091,51023.40,98139.12,10204.680,4.0,64510.426667,NaN,NaN,12902.085333
3,Smartwatch,Electronics,0.573854,-1.487424,-0.716083,2024-11-08,Debit Card,0.165002,11,2024,...,32657.81,10205.565625,44368.76,51023.40,8873.752,4.0,42683.323333,NaN,NaN,8536.664667
4,Cookware Set,Home & Kitchen,0.145962,-0.068803,0.076683,2024-12-27,UPI,0.077653,12,2024,...,26590.08,25732.335484,32657.81,44368.76,6531.562,1.0,52265.603333,NaN,NaN,10453.120667
5,Mixer Grinder,Home & Kitchen,-0.990460,-0.778114,-0.913091,2024-10-22,Wallet,-1.145231,10,2024,...,10475.03,12323.564706,79770.24,32657.81,15954.048,3.0,44459.370000,NaN,NaN,8891.874000
6,Sneakers,Clothing,0.996259,-0.068803,0.685370,2024-07-04,Wallet,-0.883184,7,2024,...,38647.72,57971.580000,20950.06,79770.24,4190.012,2.0,72221.153333,63264.650000,442852.55,14444.230667
7,Table Lamp,Home & Kitchen,0.021038,-0.068803,-0.012744,2024-12-27,Debit Card,-0.533789,12,2024,...,24818.59,31023.237500,115943.16,20950.06,23188.632,3.0,70449.663333,59881.314286,419169.20,14089.932667
8,Jacket,Clothing,-1.589002,-0.778114,-1.198736,2025-01-18,Debit Card,-0.359091,1,2025,...,1987.39,1528.761538,74455.77,115943.16,14891.154,3.0,64791.236667,53160.082857,372120.58,12958.247333
9,Tablet,Electronics,0.166161,-0.778114,-0.361112,2024-03-14,Debit Card,0.863793,3,2024,...,26876.51,13438.255000,3974.78,74455.77,794.956,2.0,44061.190000,54500.691429,381504.84,8812.238000

In [60]:
import numpy as np

In [61]:
df['price_log'] = np.log1p(df['Price (INR)'])

c:\Users\Shree\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: invalid value encountered in log1p
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [62]:
df.head()

,Product Name,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Customer Rating,Month,Year,Profit (INR),Discount %,...,Region_North,Region_South,Region_West,Payment Method_Credit Card,Payment Method_Debit Card,Payment Method_Net Banking,Payment Method_UPI,Payment Method_Wallet,Customer Segment_Retail,Customer Segment_Wholesale
0,Educational Book,1.731200,-0.778114,0.385779,2024-09-12,0.427049,9,2024,0.385779,-0.854042,...,False,False,True,False,True,False,False,False,False,False
1,Jeans,-0.829618,0.640508,-0.407043,2024-12-18,0.776444,12,2024,-0.407043,0.803302,...,True,False,False,False,False,False,True,False,False,True
2,Face Cream,-0.946938,0.640508,-0.519022,2024-05-18,1.213188,5,2024,-0.519022,0.165862,...,False,True,False,False,True,False,False,False,False,False
3,Smartwatch,0.573854,-1.487424,-0.716083,2024-11-08,0.165002,11,2024,-0.716083,-0.344090,...,True,False,False,False,True,False,False,False,False,False
4,Cookware Set,0.145962,-0.068803,0.076683,2024-12-27,0.077653,12,2024,0.076683,-0.726554,...,True,False,False,False,False,False,True,False,True,False

In [63]:
Q1 = df['Price (INR)'].quantile(0.25)
Q3 = df['Price (INR)'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

In [64]:
df = df[(df['Price (INR)'] >= lower) & (df['Price (INR)'] <= upper)]

In [66]:
df.head(10)

,Product Name,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Customer Rating,Month,Year,Profit (INR),Discount %,...,Region_North,Region_South,Region_West,Payment Method_Credit Card,Payment Method_Debit Card,Payment Method_Net Banking,Payment Method_UPI,Payment Method_Wallet,Customer Segment_Retail,Customer Segment_Wholesale
0,Educational Book,1.731200,-0.778114,0.385779,2024-09-12,0.427049,9,2024,0.385779,-0.854042,...,False,False,True,False,True,False,False,False,False,False
1,Jeans,-0.829618,0.640508,-0.407043,2024-12-18,0.776444,12,2024,-0.407043,0.803302,...,True,False,False,False,False,False,True,False,False,True
2,Face Cream,-0.946938,0.640508,-0.519022,2024-05-18,1.213188,5,2024,-0.519022,0.165862,...,False,True,False,False,True,False,False,False,False,False
3,Smartwatch,0.573854,-1.487424,-0.716083,2024-11-08,0.165002,11,2024,-0.716083,-0.344090,...,True,False,False,False,True,False,False,False,False,False
4,Cookware Set,0.145962,-0.068803,0.076683,2024-12-27,0.077653,12,2024,0.076683,-0.726554,...,True,False,False,False,False,False,True,False,True,False
5,Mixer Grinder,-0.990460,-0.778114,-0.913091,2024-10-22,-1.145231,10,2024,-0.913091,0.930790,...,True,False,False,False,False,False,False,True,False,True
6,Sneakers,0.996259,-0.068803,0.685370,2024-07-04,-0.883184,7,2024,0.685370,-0.854042,...,True,False,False,False,False,False,False,True,False,True
7,Table Lamp,0.021038,-0.068803,-0.012744,2024-12-27,-0.533789,12,2024,-0.012744,1.568230,...,False,True,False,False,True,False,False,False,False,True
8,Jacket,-1.589002,-0.778114,-1.198736,2025-01-18,-0.359091,1,2025,-1.198736,0.675814,...,True,False,False,False,True,False,False,False,False,False
9,Tablet,0.166161,-0.778114,-0.361112,2024-03-14,0.863793,3,2024,-0.361112,1.185766,...,True,False,False,False,True,False,False,False,False,False

In [69]:
df.columns

Index(['Product Name', 'Price (INR)', 'Quantity Sold', 'Total Sales (INR)',
       'Order Date', 'Customer Rating', 'Month', 'Year', 'Profit (INR)',
       'Discount %', 'day_of_week', 'is_weekend', 'calculated_sales',
       'discount_amount', 'discounted_price', 'profit_per_unit',
       'avg_order_value', 'value_per_rating', 'lag_1_sales', 'lag_2_sales',
       'lag_1_profit', 'lag_1_quantity', 'rolling_mean_sales_3',
       'rolling_mean_sales_7', 'rolling_sum_sales_7', 'rolling_mean_profit_3',
       'price_log', 'Category_Books', 'Category_Clothing',
       'Category_Electronics', 'Category_Home & Kitchen', 'Region_North',
       'Region_South', 'Region_West', 'Payment Method_Credit Card',
       'Payment Method_Debit Card', 'Payment Method_Net Banking',
       'Payment Method_UPI', 'Payment Method_Wallet',
       'Customer Segment_Retail', 'Customer Segment_Wholesale'],
      dtype='object')

In [70]:
df.shape

(1000, 41)